const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const mongoose = require('mongoose')
const cfg = require('./config')
const port = cfg.getWebServerPort()
const todosRouter = require('./routers/todos.js')
const seedDbRouter = require('./routers/seedDb.js')

app.use('/assets', express.static(`${__dirname}/public`))
app.use(bodyParser.json())
app.set('view-engine', 'ejs')
app.use('/api/setupTodos', seedDbRouter)
app.use('/api/todos', todosRouter)
mongoose.connect(cfg.getDbConnectionString())
app.listen(port)
